version: '3.7'

services:
  postgres:
    container_name: postgres_container
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whatshouldwewatchtonight_dev
    ports:
      - 5432:5432
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80

  adminer:
    image: adminer
    ports:
    - 8080:8080